#!/bin/bash
#BSUB -J "bowtie2_index_unique"
#BSUB -n 4
#BSUB -R "rusage[mem=16]"
#BSUB -W 08:00
#BSUB -q long
#BSUB -o index_unique.%J.out
#BSUB -e index_unique.%J.err

BOWTIE2_BUILD=/rs1/shares/brc/users/cysteger/conda_envs/coverm_env/bin/bowtie2-build

cd /rs1/shares/brc/users/c_s_group_3/callie_analysis/anvio_analysis

# Build index from the renamed MAGs
$BOWTIE2_BUILD all_MAGs_unique.fa all_MAGs_unique
