#!/bin/bash
#BSUB -J fastp_qc
#BSUB -o /rs1/shares/brc/users/c_s_group_3/callie_analysis/qc_results/fastp_qc_%J.out
#BSUB -e /rs1/shares/brc/users/c_s_group_3/callie_analysis/qc_results/fastp_qc_%J.err
#BSUB -n 4
#BSUB -R "rusage[mem=16]"
#BSUB -W 2:00
#BSUB -q short

source ~/.bashrc
conda activate fastp_env

R1_DIR="/rs1/shares/brc/users/c_s_group_3/NRE_MetaG_pre_post_florence/NRE_postFlo_MetaG_RAW/NVS139B_Paerl_R1"
R2_DIR="/rs1/shares/brc/users/c_s_group_3/NRE_MetaG_pre_post_florence/NRE_postFlo_MetaG_RAW/NVS139B_Paerl_R2"
OUTPUT_DIR="/rs1/shares/brc/users/c_s_group_3/callie_analysis/qc_results"

mkdir -p "$OUTPUT_DIR"

for R1 in ${R1_DIR}/*_R1_001.fastq.gz; do
    base=$(basename "$R1")
    sample=${base/_R1_001.fastq.gz/}
    R2="${R2_DIR}/${sample}_R2_001.fastq.gz"

    if [[ ! -f "$R2" ]]; then
        echo "Missing R2 for sample $sample" | tee -a "${OUTPUT_DIR}/missing_pairs.log"
        continue
    fi

    LOGFILE="${OUTPUT_DIR}/${sample}_fastp.log"

    fastp \
        -i "$R1" \
        -I "$R2" \
        -o "${OUTPUT_DIR}/${sample}_R1.trimmed.fastq.gz" \
        -O "${OUTPUT_DIR}/${sample}_R2.trimmed.fastq.gz" \
        --html "${OUTPUT_DIR}/${sample}_fastp.html" \
        --json "${OUTPUT_DIR}/${sample}_fastp.json" \
        --thread 4 \
        > "$LOGFILE" 2>&1
done
